# Generated by Django 2.0.7 on 2018-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoachRecords',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('season', models.CharField(db_column='Season', max_length=255)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('lg', models.CharField(blank=True, db_column='Lg', max_length=255, null=True)),
                ('tm', models.CharField(db_column='Tm', max_length=255)),
                ('regular_g', models.IntegerField(blank=True, db_column='regular_G', null=True)),
                ('regular_w', models.IntegerField(blank=True, db_column='regular_W', null=True)),
                ('regular_l', models.IntegerField(blank=True, db_column='regular_L', null=True)),
                ('regular_wl_ratio', models.FloatField(blank=True, null=True)),
                ('w_minus_l_over_2', models.FloatField(blank=True, null=True)),
                ('finish', models.IntegerField(blank=True, db_column='Finish', null=True)),
                ('playoff_g', models.IntegerField(blank=True, db_column='playoff_G', null=True)),
                ('playoff_w', models.IntegerField(blank=True, db_column='playoff_W', null=True)),
                ('playoff_l', models.IntegerField(blank=True, db_column='playoff_L', null=True)),
                ('playoff_wl_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coach_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchRecords',
            fields=[
                ('playoff_regular', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('g', models.IntegerField(db_column='G')),
                ('opponent', models.CharField(blank=True, db_column='Opponent', max_length=120, null=True)),
                ('home_away', models.IntegerField(blank=True, db_column='Home_away', null=True)),
                ('tm', models.IntegerField(blank=True, db_column='Tm', null=True)),
                ('opp', models.IntegerField(blank=True, db_column='Opp', null=True)),
            ],
            options={
                'db_table': 'match_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerAvgPerformance',
            fields=[
                ('number_2p', models.IntegerField(blank=True, db_column='2P', null=True)),
                ('number_2p_percent', models.FloatField(blank=True, db_column='2P_percent', null=True)),
                ('number_2pa', models.FloatField(blank=True, db_column='2PA', null=True)),
                ('number_3p', models.IntegerField(blank=True, db_column='3P', null=True)),
                ('number_3p_percent', models.FloatField(blank=True, db_column='3P_percent', null=True)),
                ('number_3pa', models.FloatField(blank=True, db_column='3PA', null=True)),
                ('ast', models.FloatField(blank=True, db_column='AST', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('blk', models.FloatField(blank=True, db_column='BLK', null=True)),
                ('drb', models.FloatField(blank=True, db_column='DRB', null=True)),
                ('fg', models.FloatField(blank=True, db_column='FG', null=True)),
                ('fg_percent', models.FloatField(blank=True, db_column='FG_percent', null=True)),
                ('fga', models.FloatField(blank=True, db_column='FGA', null=True)),
                ('ft', models.FloatField(blank=True, db_column='FT', null=True)),
                ('ft_percent', models.FloatField(blank=True, db_column='FT_percent', null=True)),
                ('fta', models.FloatField(blank=True, db_column='FTA', null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('gs', models.IntegerField(blank=True, db_column='GS', null=True)),
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('lg', models.CharField(blank=True, db_column='Lg', max_length=255, null=True)),
                ('mp', models.FloatField(db_column='MP')),
                ('orb', models.FloatField(blank=True, db_column='ORB', null=True)),
                ('pf', models.FloatField(blank=True, db_column='PF', null=True)),
                ('pts', models.FloatField(blank=True, db_column='PTS', null=True)),
                ('pos', models.CharField(blank=True, db_column='Pos', max_length=255, null=True)),
                ('stl', models.FloatField(blank=True, db_column='STL', null=True)),
                ('season', models.CharField(db_column='Season', max_length=255)),
                ('tov', models.FloatField(blank=True, db_column='TOV', null=True)),
                ('trb', models.FloatField(blank=True, db_column='TRB', null=True)),
                ('tm', models.CharField(db_column='Tm', max_length=255)),
                ('efg_percent', models.FloatField(blank=True, db_column='eFG_percent', null=True)),
            ],
            options={
                'db_table': 'player_avg_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerBasic',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('player', models.CharField(blank=True, db_column='Player', max_length=255, null=True)),
                ('start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('until', models.IntegerField(blank=True, db_column='Until', null=True)),
                ('pos', models.CharField(blank=True, db_column='Pos', max_length=255, null=True)),
                ('ht', models.CharField(blank=True, db_column='Ht', max_length=255, null=True)),
                ('wt', models.CharField(blank=True, db_column='Wt', max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, db_column='Birthday', max_length=255, null=True)),
                ('colleges', models.CharField(blank=True, db_column='Colleges', max_length=255, null=True)),
            ],
            options={
                'db_table': 'player_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerRegPerformance',
            fields=[
                ('number_3p', models.IntegerField(blank=True, db_column='3P', null=True)),
                ('number_3p_percent', models.FloatField(blank=True, db_column='3P_percent', null=True)),
                ('number_3pa', models.IntegerField(blank=True, db_column='3PA', null=True)),
                ('ast', models.IntegerField(blank=True, db_column='AST', null=True)),
                ('age', models.CharField(db_column='Age', max_length=120, primary_key=True, serialize=False)),
                ('blk', models.IntegerField(blank=True, db_column='BLK', null=True)),
                ('drb', models.IntegerField(blank=True, db_column='DRB', null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=120, null=True)),
                ('fg', models.IntegerField(blank=True, db_column='FG', null=True)),
                ('fg_percent', models.FloatField(blank=True, db_column='FG_percent', null=True)),
                ('fga', models.IntegerField(blank=True, db_column='FGA', null=True)),
                ('ft', models.IntegerField(blank=True, db_column='FT', null=True)),
                ('ft_percent', models.FloatField(blank=True, db_column='FT_percent', null=True)),
                ('fta', models.IntegerField(blank=True, db_column='FTA', null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('gs', models.CharField(blank=True, db_column='GS', max_length=255, null=True)),
                ('gmsc', models.FloatField(blank=True, db_column='GmSc', null=True)),
                ('id', models.CharField(db_column='Id', max_length=120)),
                ('mp', models.CharField(db_column='MP', max_length=255)),
                ('orb', models.IntegerField(blank=True, db_column='ORB', null=True)),
                ('opp', models.CharField(db_column='Opp', max_length=120)),
                ('pf', models.IntegerField(blank=True, db_column='PF', null=True)),
                ('pts', models.IntegerField(blank=True, db_column='PTS', null=True)),
                ('rk', models.IntegerField(blank=True, db_column='Rk', null=True)),
                ('stl', models.IntegerField(blank=True, db_column='STL', null=True)),
                ('tov', models.IntegerField(blank=True, db_column='TOV', null=True)),
                ('trb', models.IntegerField(blank=True, db_column='TRB', null=True)),
                ('tm', models.CharField(db_column='Tm', max_length=120)),
                ('home_or_awar', models.CharField(blank=True, db_column='Home_or_Awar', max_length=255, null=True)),
                ('wl', models.CharField(blank=True, db_column='WL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'player_reg_performance',
                'managed': False,
            },
        ),
    ]
