# Generated by Django 2.0.7 on 2018-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBasic',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('franchise', models.CharField(blank=True, db_column='Franchise', max_length=255, null=True)),
                ('lg', models.CharField(db_column='Lg', max_length=255)),
                ('from_yr', models.IntegerField(blank=True, db_column='From_yr', null=True)),
                ('to_yr', models.IntegerField(blank=True, db_column='To_yr', null=True)),
                ('yrs', models.IntegerField(blank=True, db_column='Yrs', null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('wl_ratio', models.FloatField(blank=True, db_column='WL_ratio', null=True)),
                ('plyfs', models.IntegerField(blank=True, db_column='Plyfs', null=True)),
                ('division', models.IntegerField(blank=True, db_column='Division', null=True)),
                ('conf', models.IntegerField(blank=True, db_column='Conf', null=True)),
                ('champ', models.IntegerField(blank=True, db_column='Champ', null=True)),
            ],
            options={
                'db_table': 'team_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamBasic2',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('franchise', models.CharField(blank=True, db_column='Franchise', max_length=255, null=True)),
                ('lg', models.CharField(db_column='Lg', max_length=255)),
                ('from_yr', models.IntegerField(blank=True, db_column='From_yr', null=True)),
                ('to_yr', models.IntegerField(blank=True, db_column='To_yr', null=True)),
                ('yrs', models.IntegerField(blank=True, db_column='Yrs', null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('wl_ratio', models.FloatField(blank=True, db_column='WL_ratio', null=True)),
                ('plyfs', models.IntegerField(blank=True, db_column='Plyfs', null=True)),
                ('division', models.IntegerField(blank=True, db_column='Division', null=True)),
                ('conf', models.IntegerField(blank=True, db_column='Conf', null=True)),
                ('champ', models.IntegerField(blank=True, db_column='Champ', null=True)),
            ],
            options={
                'db_table': 'team_basic2',
                'managed': False,
            },
        ),
    ]
